---
name: "geodash-plugin-map-map"
controllers:
  - name: GeoDashControllerMapMap
    path: GeoDashControllerMapMap.js
    handlers:
      - event: toggleComponent
        handler: toggleComponent
directives:
  - geodashMapMap.js
templates:
  - map_map.tpl.html
less:
  - map_map.less
